on: 
  push:
    branches: [main]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: ./blind_chess.py
      - run: gh release create --notes "" "$(date +%y-%m-%d)" blind_chess.apkg
