on: 
  push:
    branches: [main]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: ./blind_chess.py
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          date=$(date +%y-%m-%d)
          gh release delete --yes $date || :
          gh release create --notes "" $date blind_chess.apkg
